import { Constants } from 'eris';

export const BASE_URL = "/api/v" + Constants.REST_VERSION;
export const CDN_URL = "https://cdn.discordapp.com";
export const CLIENT_URL = "https://discord.com";

export const CHANNEL =                                                               (chanID: any) => `/channels/${chanID}`;
export const CHANNEL_BULK_DELETE =                                                   (chanID: any) => `/channels/${chanID}/messages/bulk-delete`;
export const CHANNEL_CALL_RING =                                                     (chanID: any) => `/channels/${chanID}/call/ring`;
export const CHANNEL_CROSSPOST =                                         (chanID: any, msgID: any) => `/channels/${chanID}/messages/${msgID}/crosspost`;
export const CHANNEL_FOLLOW =                                                        (chanID: any) => `/channels/${chanID}/followers`;
export const CHANNEL_INVITES =                                                       (chanID: any) => `/channels/${chanID}/invites`;
export const CHANNEL_MESSAGE_REACTION =                   (chanID: any, msgID: any, reaction: any) => `/channels/${chanID}/messages/${msgID}/reactions/${reaction}`;
export const CHANNEL_MESSAGE_REACTION_USER = (chanID: any, msgID: any, reaction: any, userID: any) => `/channels/${chanID}/messages/${msgID}/reactions/${reaction}/${userID}`;
export const CHANNEL_MESSAGE_REACTIONS =                                 (chanID: any, msgID: any) => `/channels/${chanID}/messages/${msgID}/reactions`;
export const CHANNEL_MESSAGE =                                           (chanID: any, msgID: any) => `/channels/${chanID}/messages/${msgID}`;
export const CHANNEL_MESSAGES =                                                      (chanID: any) => `/channels/${chanID}/messages`;
export const CHANNEL_MESSAGES_SEARCH =                                               (chanID: any) => `/channels/${chanID}/messages/search`;
export const CHANNEL_PERMISSION =                                       (chanID: any, overID: any) => `/channels/${chanID}/permissions/${overID}`;
export const CHANNEL_PERMISSIONS =                                                   (chanID: any) => `/channels/${chanID}/permissions`;
export const CHANNEL_PIN =                                               (chanID: any, msgID: any) => `/channels/${chanID}/pins/${msgID}`;
export const CHANNEL_PINS =                                                          (chanID: any) => `/channels/${chanID}/pins`;
export const CHANNEL_RECIPIENT =                                       (groupID: any, userID: any) => `/channels/${groupID}/recipients/${userID}`;
export const CHANNEL_TYPING =                                                        (chanID: any) => `/channels/${chanID}/typing`;
export const CHANNEL_WEBHOOKS =                                                      (chanID: any) => `/channels/${chanID}/webhooks`;
export const CHANNELS =                                                                               "/channels";
export const CUSTOM_EMOJI_GUILD =                                                   (emojiID: any) => `/emojis/${emojiID}/guild`;
export const DISCOVERY_CATEGORIES =                                                                   "/discovery/categories";
export const DISCOVERY_VALIDATION =                                                                   "/discovery/valid-term";
export const GATEWAY =                                                                                "/gateway";
export const GATEWAY_BOT =                                                                            "/gateway/bot";
export const GUILD =                                                                (guildID: any) => `/guilds/${guildID}`;
export const GUILD_AUDIT_LOGS =                                                     (guildID: any) => `/guilds/${guildID}/audit-logs`;
export const GUILD_BAN =                                             (guildID: any, memberID: any) => `/guilds/${guildID}/bans/${memberID}`;
export const GUILD_BANS =                                                           (guildID: any) => `/guilds/${guildID}/bans`;
export const GUILD_CHANNELS =                                                       (guildID: any) => `/guilds/${guildID}/channels`;
export const GUILD_DISCOVERY =                                                      (guildID: any) => `/guilds/${guildID}/discovery-metadata`;
export const GUILD_DISCOVERY_CATEGORY =                            (guildID: any, categoryID: any) => `/guilds/${guildID}/discovery-categories/${categoryID}`;
export const GUILD_EMBED =                                                          (guildID: any) => `/guilds/${guildID}/embed`;
export const GUILD_EMOJI =                                            (guildID: any, emojiID: any) => `/guilds/${guildID}/emojis/${emojiID}`;
export const GUILD_EMOJIS =                                                         (guildID: any) => `/guilds/${guildID}/emojis`;
export const GUILD_INTEGRATION =                                       (guildID: any, inteID: any) => `/guilds/${guildID}/integrations/${inteID}`;
export const GUILD_INTEGRATION_SYNC =                                  (guildID: any, inteID: any) => `/guilds/${guildID}/integrations/${inteID}/sync`;
export const GUILD_INTEGRATIONS =                                                   (guildID: any) => `/guilds/${guildID}/integrations`;
export const GUILD_INVITES =                                                        (guildID: any) => `/guilds/${guildID}/invites`;
export const GUILD_VANITY_URL =                                                     (guildID: any) => `/guilds/${guildID}/vanity-url`;
export const GUILD_MEMBER =                                          (guildID: any, memberID: any) => `/guilds/${guildID}/members/${memberID}`;
export const GUILD_MEMBER_NICK =                                     (guildID: any, memberID: any) => `/guilds/${guildID}/members/${memberID}/nick`;
export const GUILD_MEMBER_ROLE =                        (guildID: any, memberID: any, roleID: any) => `/guilds/${guildID}/members/${memberID}/roles/${roleID}`;
export const GUILD_MEMBERS =                                                        (guildID: any) => `/guilds/${guildID}/members`;
export const GUILD_MEMBERS_SEARCH =                                                 (guildID: any) => `/guilds/${guildID}/members/search`;
export const GUILD_MESSAGES_SEARCH =                                                (guildID: any) => `/guilds/${guildID}/messages/search`;
export const GUILD_PREVIEW =                                                        (guildID: any) => `/guilds/${guildID}/preview`;
export const GUILD_PRUNE =                                                          (guildID: any) => `/guilds/${guildID}/prune`;
export const GUILD_ROLE =                                              (guildID: any, roleID: any) => `/guilds/${guildID}/roles/${roleID}`;
export const GUILD_ROLES =                                                          (guildID: any) => `/guilds/${guildID}/roles`;
export const GUILD_TEMPLATE =                                                          (code: any) => `/guilds/template/${code}`;
export const GUILD_TEMPLATES =                                                      (guildID: any) => `/guilds/${guildID}/templates`;
export const GUILD_TEMPLATE_GUILD =                                      (guildID: any, code: any) => `/guilds/${guildID}/templates/${code}`;
export const GUILD_VOICE_REGIONS =                                                  (guildID: any) => `/guilds/${guildID}/regions`;
export const GUILD_WEBHOOKS =                                                       (guildID: any) => `/guilds/${guildID}/webhooks`;
export const GUILD_WELCOME_SCREEN =                                                 (guildID: any) => `/guilds/${guildID}/welcome-screen`;
export const GUILD_WIDGET =                                                         (guildID: any) => `/guilds/${guildID}/widget`;
export const GUILD_VOICE_STATE =                                         (guildID: any, user: any) => `/guilds/${guildID}/voice-states/${user}`;
export const GUILDS =                                                                                  "/guilds";
export const INVITE =                                                              (inviteID: any) => `/invite/${inviteID}`;
export const OAUTH2_APPLICATION =                                                     (appID: any) => `/oauth2/applications/${appID}`;
export const USER =                                                                  (userID: any) => `/users/${userID}`;
export const USER_BILLING =                                                          (userID: any) => `/users/${userID}/billing`;
export const USER_BILLING_PAYMENTS =                                                 (userID: any) => `/users/${userID}/billing/payments`;
export const USER_BILLING_PREMIUM_SUBSCRIPTION =                                     (userID: any) => `/users/${userID}/billing/premium-subscription`;
export const USER_CHANNELS =                                                         (userID: any) => `/users/${userID}/channels`;
export const USER_CONNECTIONS =                                                      (userID: any) => `/users/${userID}/connections`;
export const USER_CONNECTION_PLATFORM =                      (userID: any, platform: any, id: any) => `/users/${userID}/connections/${platform}/${id}`;
export const USER_GUILD =                                              (userID: any, guildID: any) => `/users/${userID}/guilds/${guildID}`;
export const USER_GUILDS =                                                           (userID: any) => `/users/${userID}/guilds`;
export const USER_MFA_CODES =                                                        (userID: any) => `/users/${userID}/mfa/codes`;
export const USER_MFA_TOTP_DISABLE =                                                 (userID: any) => `/users/${userID}/mfa/totp/disable`;
export const USER_MFA_TOTP_ENABLE =                                                  (userID: any) => `/users/${userID}/mfa/totp/enable`;
export const USER_NOTE =                                              (userID: any, targetID: any) => `/users/${userID}/note/${targetID}`;
export const USER_PROFILE =                                                          (userID: any) => `/users/${userID}/profile`;
export const USER_RELATIONSHIP =                                         (userID: any, relID: any) => `/users/${userID}/relationships/${relID}`;
export const USER_SETTINGS =                                                         (userID: any) => `/users/${userID}/settings`;
export const USERS =                                                                                   "/users";
export const VOICE_REGIONS =                                                                           "/voice/regions";
export const WEBHOOK =                                                               (hookID: any) => `/webhooks/${hookID}`;
export const WEBHOOK_MESSAGE =                               (hookID: any, token: any, msgID: any) => `/webhooks/${hookID}/${token}/messages/${msgID}`;
export const WEBHOOK_SLACK =                                                         (hookID: any) => `/webhooks/${hookID}/slack`;
export const WEBHOOK_TOKEN =                                             (hookID: any, token: any) => `/webhooks/${hookID}/${token}`;
export const WEBHOOK_TOKEN_SLACK =                                       (hookID: any, token: any) => `/webhooks/${hookID}/${token}/slack`;

// CDN Endpoints
export const ACHIEVEMENT_ICON =           (applicationID: any, achievementID: any, icon: any) => `/app-assets/${applicationID}/achievements/${achievementID}/icons/${icon}`;
export const APPLICATION_ASSET =                        (applicationID: any, asset: any) => `/app-assets/${applicationID}/${asset}`;
export const APPLICATION_ICON =                          (applicationID: any, icon: any) => `/app-icons/${applicationID}/${icon}`;
export const CHANNEL_ICON =                                 (chanID: any, chanIcon: any) => `/channel-icons/${chanID}/${chanIcon}`;
export const CUSTOM_EMOJI =                                          (emojiID: any) => `/emojis/${emojiID}`;
export const DEFAULT_USER_AVATAR =                         (userDiscriminator: any) => `/embed/avatars/${userDiscriminator}`;
export const GUILD_BANNER =                             (guildID: any, guildBanner: any) => `/banners/${guildID}/${guildBanner}`;
export const GUILD_DISCOVERY_SPLASH =          (guildID: any, guildDiscoverySplash: any) => `/discovery-splashes/${guildID}/${guildDiscoverySplash}`;
export const GUILD_ICON =                                 (guildID: any, guildIcon: any) => `/icons/${guildID}/${guildIcon}`;
export const GUILD_SPLASH =                             (guildID: any, guildSplash: any) => `/splashes/${guildID}/${guildSplash}`;
export const TEAM_ICON                                    = (teamID: any, teamIcon: any) => `/team-icons/${teamID}/${teamIcon}`;
export const USER_AVATAR =                                (userID: any, userAvatar: any) => `/avatars/${userID}/${userAvatar}`;

// Client Endpoints
export const MESSAGE_LINK =                    (guildID: any, channelID: any, messageID: any) => `/channels/${guildID}/${channelID}/${messageID}`;
